/**
 * Hardcoded demo data served on demo.aileplan.uk.
 *
 * Story: Lukas (junior software dev, ~28) and Anna (university student
 * + part-time tutor, ~26) live in a 2-bedroom rental in Vienna's 7th
 * district (Neubau). Combined net income ~€3,600/month, realistic
 * Austrian middle-class budget (Wien Energie, Wiener Linien Jahreskarte,
 * ÖAMTC, Pickerl, Parkpickerl 7. Bezirk). They own a cat named Cleo.
 *
 * Numbers tuned so savings goal projections roughly hold
 * (currentAmount + monthlyAllocation × monthsRemaining ≈ targetAmount).
 * All snapshots dated 2026-05-01.
 *
 * Owner mapping for the existing UI:
 *   Lukas → Benim
 *   Anna  → Esim
 *   shared → Ev
 */
import type { FamilyBudget } from "../../drizzle/schema";

const DEMO_DATE = "2026-05-01";

const incomes = [
  {
    id: "demo-i-1",
    name: "Lukas Gehalt (Junior Dev)",
    amount: 2300,
    type: "Sabit",
    owner: "Benim",
    date: DEMO_DATE,
    notes: "Netto, nach Steuern",
  },
  {
    id: "demo-i-2",
    name: "Anna Stipendium + Tutorin",
    amount: 900,
    type: "Sabit",
    owner: "Esim",
    date: DEMO_DATE,
    notes: "Studienbeihilfe + Nachhilfe",
  },
  {
    id: "demo-i-3",
    name: "Anna Freelance Design",
    amount: 400,
    type: "Ek",
    owner: "Esim",
    date: "2026-05-15",
    notes: "Monatlicher Durchschnitt, variabel",
  },
];

const expenses = [
  {
    id: "demo-e-1",
    category: "Konut",
    subcategory: "Miete (2BR Neubau)",
    type: "Sabit",
    amount: 950,
    paymentDay: "1",
    status: "Odendi",
    owner: "Ev",
    notes: "7. Bezirk, inkl. Betriebskosten",
  },
  {
    id: "demo-e-2",
    category: "Konut",
    subcategory: "Wien Energie",
    type: "Sabit",
    amount: 120,
    paymentDay: "15",
    status: "Bekliyor",
    owner: "Ev",
    notes: "Strom + Gas, Monatsdurchschnitt",
  },
  {
    id: "demo-e-3",
    category: "Konut",
    subcategory: "Magenta Glasfaser",
    type: "Sabit",
    amount: 30,
    paymentDay: "5",
    status: "Odendi",
    owner: "Ev",
    notes: "300 Mbit Glasfaser",
  },
  {
    id: "demo-e-4",
    category: "Konut",
    subcategory: "Drei Familytarif",
    type: "Sabit",
    amount: 40,
    paymentDay: "10",
    status: "Odendi",
    owner: "Ev",
    notes: "2 SIM-Karten",
  },
  {
    id: "demo-e-5",
    category: "Konut",
    subcategory: "ORF Beitrag",
    type: "Sabit",
    amount: 15,
    paymentDay: "12",
    status: "Odendi",
    owner: "Ev",
    notes: "ORF-Beitrag (ehem. GIS)",
  },
  {
    id: "demo-e-6",
    category: "Abonelik",
    subcategory: "Netflix Standard",
    type: "Sabit",
    amount: 13,
    paymentDay: "8",
    status: "Odendi",
    owner: "Ev",
    notes: "Standard mit Werbung",
  },
  {
    id: "demo-e-7",
    category: "Abonelik",
    subcategory: "Spotify Familie",
    type: "Sabit",
    amount: 18,
    paymentDay: "8",
    status: "Odendi",
    owner: "Ev",
    notes: "Family-Abo",
  },
  {
    id: "demo-e-8",
    category: "Abonelik",
    subcategory: "YouTube Premium",
    type: "Sabit",
    amount: 13,
    paymentDay: "8",
    status: "Odendi",
    owner: "Ev",
    notes: "",
  },
  {
    id: "demo-e-9",
    category: "Ulasim",
    subcategory: "Wiener Linien Jahreskarte",
    type: "Sabit",
    amount: 33,
    paymentDay: "1",
    status: "Odendi",
    owner: "Benim",
    notes: "365€/Jahr, monatlich aufgeteilt",
  },
  {
    id: "demo-e-10",
    category: "Yiyecek",
    subcategory: "Billa Wocheneinkauf",
    type: "Degisken",
    amount: 120,
    status: "Odendi",
    owner: "Ev",
    notes: "Wöchentlich, Monatsdurchschnitt",
  },
  {
    id: "demo-e-11",
    category: "Yiyecek",
    subcategory: "Würstelstand am Naschmarkt",
    type: "Degisken",
    amount: 25,
    status: "Odendi",
    owner: "Esim",
    notes: "",
  },
  {
    id: "demo-e-12",
    category: "Yiyecek",
    subcategory: "Café Sperl",
    type: "Degisken",
    amount: 18,
    status: "Odendi",
    owner: "Esim",
    notes: "Wiener Kaffeehaus",
  },
  {
    id: "demo-e-13",
    category: "AI",
    subcategory: "Claude Pro",
    type: "Sabit",
    amount: 22.5,
    paymentDay: "15",
    status: "Bekliyor",
    owner: "Benim",
    notes: "Pro-Abo",
  },
  {
    id: "demo-e-14",
    category: "AI",
    subcategory: "GitHub Copilot",
    type: "Sabit",
    amount: 10,
    paymentDay: "15",
    status: "Bekliyor",
    owner: "Benim",
    notes: "",
  },
  {
    id: "demo-e-15",
    category: "KisiselBakim",
    subcategory: "Friseur Müller",
    type: "Degisken",
    amount: 35,
    paymentDay: "5",
    status: "Odendi",
    owner: "Esim",
    notes: "",
  },
  {
    id: "demo-e-16",
    category: "Tabak",
    subcategory: "Snus Pouches",
    type: "Sabit",
    amount: 18,
    paymentDay: "10",
    status: "Odendi",
    owner: "Benim",
    notes: "",
  },
  {
    id: "demo-e-17",
    category: "Araba",
    subcategory: "OMV Tankstelle",
    type: "Sabit",
    amount: 120,
    paymentDay: "25",
    status: "Bekliyor",
    owner: "Ev",
    notes: "Monatsdurchschnitt",
  },
  {
    id: "demo-e-18",
    category: "Tatil",
    subcategory: "Schönbrunn Familienkarte",
    type: "Degisken",
    amount: 28,
    paymentDay: "1",
    status: "Odendi",
    owner: "Ev",
    notes: "Jahreskarte Tiergarten",
  },
  {
    id: "demo-e-19",
    category: "Loto",
    subcategory: "Lotto Wien",
    type: "Degisken",
    amount: 5,
    paymentDay: "3",
    status: "Odendi",
    owner: "Benim",
    notes: "",
  },
  {
    id: "demo-e-20",
    category: "Saglik",
    subcategory: "Apotheke Burggasse",
    type: "Degisken",
    amount: 28,
    paymentDay: "12",
    status: "Odendi",
    owner: "Benim",
    notes: "Rezeptgebühr + Vitamine",
  },
  {
    id: "demo-e-21",
    category: "KisiselBakim",
    subcategory: "dm Drogerie",
    type: "Degisken",
    amount: 35,
    paymentDay: "18",
    status: "Odendi",
    owner: "Esim",
    notes: "",
  },
  {
    id: "demo-e-22",
    category: "Araba",
    subcategory: "Eni Tankstelle",
    type: "Degisken",
    amount: 65,
    paymentDay: "20",
    status: "Bekliyor",
    owner: "Ev",
    notes: "Variable Zweittankung",
  },
  {
    id: "demo-e-23",
    category: "Ulasim",
    subcategory: "Wiener Linien Einzelfahrt",
    type: "Degisken",
    amount: 12,
    paymentDay: "8",
    status: "Odendi",
    owner: "Esim",
    notes: "Einzeltickets",
  },
  {
    id: "demo-e-24",
    category: "Eglence",
    subcategory: "Kino Gartenbaukino",
    type: "Degisken",
    amount: 24,
    paymentDay: "22",
    status: "Odendi",
    owner: "Ev",
    notes: "",
  },
];

const debts = [
  {
    id: "demo-d-1",
    name: "HSBC Kreditkarte",
    totalDebt: 450,
    monthlyPayment: 0,
    dueDate: "2026-09-30",
    status: "Bekliyor",
    owner: "Benim",
    notes: "Keine feste Monatsrate",
  },
  {
    id: "demo-d-2",
    name: "Möbelix Möbelkredit",
    totalDebt: 380,
    monthlyPayment: 95,
    dueDate: "2026-10-31",
    status: "Bekliyor",
    owner: "Ev",
    notes: "6 Raten, 3 bereits bezahlt",
  },
];

const installments = [
  {
    id: "demo-t-1",
    name: "iPhone 13 (Drei Plan)",
    totalAmount: 1200,
    installmentCount: 12,
    monthlyAmount: 100,
    startYear: 2026,
    startMonth: 4,
    owner: "Benim",
    notes: "Gerätekredit über Drei",
  },
  {
    id: "demo-t-2",
    name: "MacBook Air M2 (Apple Education)",
    totalAmount: 2400,
    installmentCount: 24,
    monthlyAmount: 100,
    startYear: 2026,
    startMonth: 2,
    owner: "Benim",
    notes: "Apple Education Finanzierung",
  },
  {
    id: "demo-t-3",
    name: "Geschirrspüler (Saturn 0% Finanzierung)",
    totalAmount: 600,
    installmentCount: 6,
    monthlyAmount: 100,
    startYear: 2026,
    startMonth: 2,
    owner: "Ev",
    notes: "0% Finanzierung",
  },
  {
    id: "demo-t-4",
    name: "Sofa (XXXLutz)",
    totalAmount: 1800,
    installmentCount: 18,
    monthlyAmount: 100,
    startYear: 2026,
    startMonth: 1,
    owner: "Ev",
    notes: "18 Raten, 0% Aktion",
  },
  {
    id: "demo-t-5",
    name: "E-Bike (Radwelt)",
    totalAmount: 2400,
    installmentCount: 24,
    monthlyAmount: 100,
    startYear: 2026,
    startMonth: 3,
    owner: "Esim",
    notes: "24 Monatsraten",
  },
];

const annualPayments = [
  {
    id: "demo-y-1",
    name: "Autoversicherung",
    amount: 890,
    paymentMonth: 3,
    paymentDay: 15,
    lastPaymentDate: "2026-03-15",
    notes: "Donau Versicherung — Kasko + Haftpflicht",
    owner: "Ev",
    category: "Araba",
    subcategoryKey: "Sigorta",
  },
  {
    id: "demo-y-2",
    name: "Vignette",
    amount: 100,
    paymentMonth: 1,
    paymentDay: 10,
    lastPaymentDate: "2026-01-10",
    notes: "Autobahn-Jahresvignette",
    owner: "Ev",
    category: "Araba",
    subcategoryKey: "Vignette",
  },
  {
    id: "demo-y-3",
    name: "ÖAMTC Jahresgebühr",
    amount: 170,
    paymentMonth: 1,
    paymentDay: 20,
    lastPaymentDate: "2026-01-20",
    notes: "Pannenhilfe-Mitgliedschaft",
    owner: "Ev",
    category: "Araba",
    subcategoryKey: "OAMTC",
  },
  {
    id: "demo-y-4",
    name: "Parkpickerl 7. Bezirk",
    amount: 280,
    paymentMonth: 1,
    paymentDay: 15,
    lastPaymentDate: "2026-01-15",
    notes: "Anwohnerparken Neubau",
    owner: "Ev",
    category: "Araba",
    subcategoryKey: "Parkpickerl",
  },
  {
    id: "demo-y-5",
    name: "Cleo Tierarzt jährlich",
    amount: 95,
    paymentMonth: 5,
    paymentDay: 12,
    lastPaymentDate: "2025-05-12",
    notes: "Impfung + Kontrolle",
    owner: "Ev",
    category: "Porsuk",
    subcategoryKey: "Veteriner",
  },
  {
    id: "demo-y-6",
    name: "Hausratversicherung",
    amount: 240,
    paymentMonth: 4,
    paymentDay: 5,
    lastPaymentDate: "2026-04-05",
    notes: "Wohnungs- + Haushaltsversicherung",
    owner: "Ev",
    category: "Konut",
    subcategoryKey: "Versicherung",
  },
  {
    id: "demo-y-7",
    name: "Fitness-Studio Jahresabo",
    amount: 480,
    paymentMonth: 1,
    paymentDay: 8,
    lastPaymentDate: "2026-01-08",
    notes: "Jahresabo Fitnessstudio",
    owner: "Benim",
    category: "Spor",
    subcategoryKey: "Uyelik",
  },
];

const budgetLimits = [
  { id: "demo-l-1", category: "Yiyecek", limit: 700, owner: "Ev" },
  { id: "demo-l-2", category: "Eglence", limit: 120, owner: "Ev" },
  { id: "demo-l-3", category: "Ulasim", limit: 60, owner: "Ev" },
  { id: "demo-l-4", category: "Porsuk", limit: 80, owner: "Ev" },
  { id: "demo-l-5", category: "Araba", limit: 250, owner: "Ev" },
  { id: "demo-l-6", category: "Tatil", limit: 400, owner: "Ev" },
];

const savingsGoals = [
  // Snapshot 2026-05-01. Math: current + monthly × monthsRemaining ≈ target.
  {
    id: "demo-s-1",
    name: "Urlaub 2026 (Italien)",
    targetAmount: 8000,
    currentAmount: 5500,
    monthlyAllocation: 350,
    targetDate: "2026-12-31",
    owner: "Ev",
    notes: "Toskana-Roadtrip, 2 Wochen",
  },
  {
    id: "demo-s-2",
    name: "Neuer Gebrauchtwagen",
    targetAmount: 18000,
    currentAmount: 4200,
    monthlyAllocation: 500,
    targetDate: "2028-01-31",
    owner: "Ev",
    notes: "Kombi, max. 3 Jahre alt",
  },
  {
    id: "demo-s-3",
    name: "Notfallfonds",
    targetAmount: 10000,
    currentAmount: 4500,
    monthlyAllocation: 200,
    targetDate: "2027-12-31",
    owner: "Ev",
    notes: "3 Monatsausgaben Rücklage",
  },
  {
    id: "demo-s-4",
    name: "Hochzeitsfonds",
    targetAmount: 5000,
    currentAmount: 1200,
    monthlyAllocation: 150,
    targetDate: "2027-09-30",
    owner: "Ev",
    notes: "Standesamt + Feier",
  },
  {
    id: "demo-s-5",
    name: "Wohnung Renovierung",
    targetAmount: 6500,
    currentAmount: 800,
    monthlyAllocation: 200,
    targetDate: "2027-06-30",
    owner: "Ev",
    notes: "Küche + Bad",
  },
];

export const DEMO_FAMILY_BUDGET: FamilyBudget = {
  id: 0,
  familyId: "demo",
  incomes: JSON.stringify(incomes),
  expenses: JSON.stringify(expenses),
  debts: JSON.stringify(debts),
  annualPayments: JSON.stringify(annualPayments),
  budgetLimits: JSON.stringify(budgetLimits),
  savingsGoals: JSON.stringify(savingsGoals),
  installments: JSON.stringify(installments),
  updatedAt: new Date(`${DEMO_DATE}T12:00:00.000Z`),
};

export const DEMO_PROFILES = [
  { id: "demo-lukas", name: "Lukas", emoji: "👨", person: "Benim" as const },
  { id: "demo-anna", name: "Anna", emoji: "👩", person: "Esim" as const },
];

export type DemoProfileId = (typeof DEMO_PROFILES)[number]["id"];
